### PR TITLE
Run shellcheck as GitHub action in tomcatjss CI

### PR DESCRIPTION
**Pull request by ckelleyRH**
* Rename sonarcloud.yml to code-analysis.yml, add any additonal future
linters/scanners into this workflow.

### CODE REVIEW

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
Thanks @fmarco76 !

**Comment by edewata** [comment]
Looks like it's still called `sonarcloud.yml`. Feel free to fix that directly.

**Comment by ckelleyRH** [comment]
Oops! Done.

**Pull request merged**
